### ISSUE TITLE
LLPC fails with LLVM fatal error: "PHI node has multiple entries for the same basic block with different incoming values!"

### ISSUE THREAD

**Issue by afd** [GPUOpen-Drivers/llpc#1034] opened 2020-11-12 16:23 UTC
Running LLPC with IR verification on one of the attached shaders leads to a fatal error.

llpc revision: c877ce19d1af35a04abe5d2b49702eaa49061b8a
llvm-project revision: 88613f67ca2e3e64cc1c7c4ccd47e126495e6e23

[tofile.zip](https://github.com/GPUOpen-Drivers/llpc/files/5531836/tofile.zip)

```
amdllpc small.spv -val=false -verify-ir -o temp.out
PHI node has multiple entries for the same basic block with different incoming values!
  %__llpc_output_proxy_.0.2 = phi float [ undef, %21 ], [ 1.000000e+00, %21 ], [ 5.000000e-01, %.entry ]
label %21
float 1.000000e+00
float undef
in function _amdgpu_ps_main
ERROR: LLVM FATAL ERROR: Broken function found, compilation aborted!
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
```

**Comment by afd** [comment] 2020-11-12 16:23
I will add a shader-db test in due course.

**Comment by ruiling** [comment] 2020-11-24 08:39
The issue is fixed by: https://github.com/GPUOpen-Drivers/llvm-project/commit/45db5159fc98e8597deb66417f6c43e7f47010c8

**Closed** 2021-01-21 05:36 UTC
