### ISSUE TITLE
PatchInOutImportExport shouldn't visit whole functions

### ISSUE THREAD

**Issue by jayfoad** [GPUOpen-Drivers/llpc#724] opened 2020-05-27 16:05 UTC
The PatchInOutImportExport pass visits whole functions to find the call and return instructions. I think it would be more efficient to find the call instructions by iterating over users of the callee, and return instructions by looking at the terminator of each basic block. This should be faster when visiting very large functions with very few call and return instructions.

**Comment by ruiling** [comment] 2020-09-04 07:15
I am analyzing failures of in CTS caused by #939. One of the issue is about tracking m_lastExport, the existing implementation visiting the instructions in order and easily track and update the m_lastExport to set 'Done' flag to the very last export instruction. @amdrexu  suggest me to delay the position0 export as the last export to position in the last block. so we don't need to track last export anymore. I am working on implement this.

**Comment by ruiling** [comment] 2020-11-10 06:26
Let's close the issue since #939 was merged.

**Closed by ruiling** 2020-11-10 06:26 UTC
Labels: enhancement

**Comment by jayfoad** [comment] 2020-11-10 07:38
Thank you!
